### ISSUE TITLE
Mac OS Build for v1.0.0-beta.2020.12.14 

### ISSUE THREAD

**Issue by lentz** [jac241/power_hour_creator#65]
Any chance you could create a Mac OS build for the latest release (v1.0.0-beta.2020.12.14)? The previous build for Mac OS is having an error downloading videos with "Unable to extract video data". I attempted to build the Mac OS version from source, but get the following error when building (I haven't used python before so perhaps I have something misconfigured):
```
Traceback (most recent call last):
  File "/usr/local/bin/pyinstaller", line 8, in <module>
    sys.exit(run())
  File "/usr/local/Cellar/pyinstaller/4.2/libexec/lib/python3.9/site-packages/PyInstaller/__main__.py", line 114, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/usr/local/Cellar/pyinstaller/4.2/libexec/lib/python3.9/site-packages/PyInstaller/__main__.py", line 65, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/usr/local/Cellar/pyinstaller/4.2/libexec/lib/python3.9/site-packages/PyInstaller/building/build_main.py", line 725, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/usr/local/Cellar/pyinstaller/4.2/libexec/lib/python3.9/site-packages/PyInstaller/building/build_main.py", line 672, in build
    exec(code, spec_namespace)
  File "power_hour_creator.spec", line 64, in <module>
    coll = COLLECT(folder_exe,
  File "/usr/local/Cellar/pyinstaller/4.2/libexec/lib/python3.9/site-packages/PyInstaller/building/api.py", line 709, in __init__
    self.__postinit__()
  File "/usr/local/Cellar/pyinstaller/4.2/libexec/lib/python3.9/site-packages/PyInstaller/building/datastruct.py", line 160, in __postinit__
    self.assemble()
  File "/usr/local/Cellar/pyinstaller/4.2/libexec/lib/python3.9/site-packages/PyInstaller/building/api.py", line 736, in assemble
    os.makedirs(todir)
  File "/usr/local/Cellar/python@3.9/3.9.1_8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/local/Cellar/python@3.9/3.9.1_8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
NotADirectoryError: [Errno 20] Not a directory: '/Users/myuser/projects/power_hour_creator/dist/Power Hour Creator/power_hour_creator/db'
```
Thanks!

**Comment by jac241** [comment]
sure give me a min

**Comment by jac241** [comment]
https://github.com/jac241/power_hour_creator/releases/tag/v1.0.0-beta.2021.02.10

**Comment by lentz** [comment]
Confirmed it's working on Mac OS again - thanks so much!
